apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: ghost
data:
  default.conf: |
    server {
      listen *:80;
      server_name _;

      location / {
        proxy_pass http://ghost:2368;
      }
    }
